"""
Stinger V2 Configuration
stinger.swarmbee.eth
"""

import os
from pathlib import Path
from typing import Optional
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    """Stinger V2 configuration"""
    
    # ==========================================================================
    # SERVICE URLS
    # ==========================================================================
    queenbee_url: str = os.getenv("QUEENBEE_URL", "http://192.168.0.52:8200")
    bumble_url: str = os.getenv("BUMBLE_URL", "http://192.168.0.250:8000")
    stinger_url: str = os.getenv("STINGER_URL", "http://192.168.0.99:8100")
    ipfs_gateway: str = os.getenv("IPFS_GATEWAY", "http://localhost:5001")
    
    # ==========================================================================
    # PATHS
    # ==========================================================================
    classifier_model_path: Path = Path(os.getenv(
        "CLASSIFIER_MODEL_PATH",
        "/opt/stinger/models/classifier.pt"
    ))
    output_dir: Path = Path(os.getenv("OUTPUT_DIR", "/opt/stinger/outputs"))
    ledger_db_path: Path = Path(os.getenv("LEDGER_DB_PATH", "/opt/stinger/ledger.db"))
    gold_prompts_dir: Path = Path(os.getenv(
        "GOLD_PROMPTS_DIR",
        "/opt/stinger/prompts"
    ))
    
    # ==========================================================================
    # CRYPTO
    # ==========================================================================
    signer_private_key: Optional[str] = os.getenv("SIGNER_PRIVATE_KEY")
    ens_domain: str = "stinger.swarmbee.eth"
    chain_id: int = 1  # Ethereum mainnet
    
    # ==========================================================================
    # GPU FLEET
    # ==========================================================================
    gpu_endpoints: list = [
        {"name": "bumble-0", "url": "http://192.168.0.250:8000", "gpus": 2, "type": "5090"},
        {"name": "bumble-1", "url": "http://192.168.0.251:8000", "gpus": 2, "type": "5090"},
        {"name": "bumble-2", "url": "http://192.168.0.252:8000", "gpus": 4, "type": "6000ada"},
    ]
    
    # ==========================================================================
    # PROCESSING
    # ==========================================================================
    max_concurrent_jobs: int = int(os.getenv("MAX_CONCURRENT_JOBS", "10"))
    job_timeout_seconds: int = int(os.getenv("JOB_TIMEOUT_SECONDS", "300"))
    enable_caching: bool = os.getenv("ENABLE_CACHING", "true").lower() == "true"
    
    # ==========================================================================
    # REPORTING
    # ==========================================================================
    report_header_text: str = "TrustCat Medical AI Report"
    report_footer_text: str = "Generated by Stinger V2 — stinger.swarmbee.eth"
    include_disclaimer: bool = True
    disclaimer_text: str = """
    DISCLAIMER: This report was generated by artificial intelligence and is intended 
    for clinical decision support only. It does not constitute a medical diagnosis. 
    All findings should be verified by a qualified healthcare professional.
    """
    
    # ==========================================================================
    # EPOCH SETTINGS
    # ==========================================================================
    epoch_duration_hours: int = 24
    epoch_min_jobs: int = 1
    auto_seal_epochs: bool = True
    
    # ==========================================================================
    # ENS IDENTITIES
    # ==========================================================================
    ens_identities: dict = {
        "stinger": "stinger.swarmbee.eth",
        "queenbee": "queenbee.swarmbee.eth",
        "bumble": "bumble.swarmbee.eth",
        "swarmpool": "swarmpool.swarmbee.eth",
        "merlin": "merlin.swarmbee.eth",
    }
    
    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"


# Global settings instance
settings = Settings()
